Decision_Tree: 
  - criterion:
    - entropy
    - gini
  - splitter:
    - random
    - best
  - min_weight_fraction_leaf:
    - 0.0
    - 0.0025
    - 0.005
    - 0.0075
    - 0.01
    - 0.02
  - min_samples_split:
    - 2
    - 3
    - 4
    - 5
    - 6
    - 8
    - 10
  - min_samples_leaf:
    - 1
    - 0.01
    - 0.02
    - 0.03
    - 0.04
  - min_impurity_decrease:
    - 0.0
    - 0.0005
    - 0.005
    - 0.05
    - 0.10
    - 0.15
    - 0.2
  - max_leaf_nodes:
    - 10
    - 15
    - 20
    - 25
    - 30
    - 35
    - 40
    - 45
    - 50
    - 55
    - null
  - max_depth:
    - null
    - 2
    - 4
    - 6
    - 8
  - min_weight_fraction_leaf:
    - 0.0
    - 0.0025
    - 0.005
    - 0.0075
    - 0.01
    - 0.05


Random_Forest:
  - min_samples_leaf:
    - 1
    - 2
    - 4
    - 6
    - 8
    - 10
    - 20
    - 30
  - min_impurity_decrease:
    - 0.0
    - 0.01
    - 0.05
    - 0.10
    - 0.15
    - 0.2
  - max_depth:
    - 2
    - 4
    - 6
    - 8
    - 10
    - 20 

SVC:
  - kernel:
    - rbf
  - C:
    - 0.1
    - 1
    - 10
    - 100
    - 1000
  - gamma:
    - 1
    - 0.1
    - 0.01
    - 0.001
    - 0.0001